[tasks.resbuild]
script_runner="python"
script_extension = "py"
script='''
from distutils.dir_util import copy_tree
copy_tree("res", "target/release")
'''

[tasks.resdebug]
script_runner="python"
script_extension = "py"
script='''
from distutils.dir_util import copy_tree
copy_tree("res", "target/debug")
'''

[tasks.release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["resbuild"]

[tasks.debug]
command = "cargo"
args = ["build"]
dependencies = ["resdebug"]
