[package]
name = "rust-alert"
version = "0.1.0"
edition = "2021"
description = "Structures and utilities for C&C formats written in Rust."
license = "MIT"

[dependencies]
bitflags = "2.4.1"
blowfish = { version = "0.9.1", features = ["bcrypt"] }
clap = { version = "4.4.7", features = ["derive"], optional = true }
rand = "0.8.5"
crc32fast = "1.3.2"
indexmap = "2.0.2"
num-bigint = "0.4.4"
serde = { version = "1.0.196", features = ["derive"], optional = true }
sha1 = "0.10.6"
thiserror = "1.0.49"

[features]
default = []
clap = ["dep:clap"]
serde = ["dep:serde"]
